[build]
builder = "nixpacks"

[deploy]
healthcheckPath = "/api/v1/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"

# Backend service configuration
[[services]]
name = "backend"
source = "backend"

[services.env]
NODE_VERSION = "20.18.1"
NPM_VERSION = "10.2.4"

[services.build]
buildCommand = "npm install && npm run build"

[services.deploy]
startCommand = "npm run start:prod"
healthcheckPath = "/api/v1/health"

[[services.ports]]
port = 5000
protocol = "http"

# Frontend service configuration  
[[services]]
name = "frontend"
source = "frontend"

[services.env]
NODE_VERSION = "20.18.1"
NPM_VERSION = "10.2.4"

[services.build]
buildCommand = "npm install && npm run build"

[services.deploy]
startCommand = "npm start"

[[services.ports]]
port = 3000
protocol = "http" 