[variables]
NODE_VERSION = "20.18.1"
NPM_VERSION = "10.2.4"

[phases.setup]
nixPkgs = ["nodejs_20", "npm-9_x"]

[phases.install]
cmds = ["npm ci"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npm run start:prod" 